# Generated by Django 3.2.18 on 2024-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmarc', '0009_auto_20170109_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbreport',
            name='description',
            field=models.TextField(blank=True, verbose_name='human readable feedback'),
        ),
        migrations.AlterField(
            model_name='fbreport',
            name='email_source',
            field=models.TextField(blank=True, verbose_name='source email including rfc822 headers'),
        ),
        migrations.AlterField(
            model_name='fbreporter',
            name='org_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='policy_adkim',
            field=models.CharField(max_length=1, verbose_name='DKIM alignment mode'),
        ),
        migrations.AlterField(
            model_name='report',
            name='policy_aspf',
            field=models.CharField(max_length=1, verbose_name='SPF alignment mode'),
        ),
        migrations.AlterField(
            model_name='report',
            name='policy_p',
            field=models.CharField(max_length=10, verbose_name='Requested handling policy'),
        ),
        migrations.AlterField(
            model_name='report',
            name='policy_pct',
            field=models.SmallIntegerField(verbose_name='Sampling rate'),
        ),
        migrations.AlterField(
            model_name='report',
            name='policy_sp',
            field=models.CharField(max_length=10, verbose_name='Requested handling policy for subdomains'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='org_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Organisation'),
        ),
    ]
